# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loader_widgets.ui'
#
# Created: Wed Feb 03 20:48:08 2021
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1163, 653)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(50)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.box_segement = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.box_segement.setFont(font)
        self.box_segement.setObjectName("box_segement")
        self.box_segement.addItem("")
        self.box_segement.addItem("")
        self.horizontalLayout.addWidget(self.box_segement)
        self.horizontalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(50)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.box_version = QtWidgets.QComboBox(self.centralwidget)
        self.box_version.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.box_version.setFont(font)
        self.box_version.setObjectName("box_version")
        self.box_version.addItem("")
        self.box_version.addItem("")
        self.box_version.addItem("")
        self.box_version.addItem("")
        self.horizontalLayout_2.addWidget(self.box_version)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.btn_fresh = QtWidgets.QPushButton(self.centralwidget)
        self.btn_fresh.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.btn_fresh.setFont(font)
        self.btn_fresh.setObjectName("btn_fresh")
        self.horizontalLayout_5.addWidget(self.btn_fresh)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.lst_img_area = QtWidgets.QListWidget(self.centralwidget)
        self.lst_img_area.setObjectName("lst_img_area")
        self.gridLayout.addWidget(self.lst_img_area, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_freshpreview = QtWidgets.QPushButton(self.centralwidget)
        self.btn_freshpreview.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.btn_freshpreview.setFont(font)
        self.btn_freshpreview.setObjectName("btn_freshpreview")
        self.horizontalLayout_6.addWidget(self.btn_freshpreview)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.btn_load = QtWidgets.QPushButton(self.centralwidget)
        self.btn_load.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.btn_load.setFont(font)
        self.btn_load.setObjectName("btn_load")
        self.horizontalLayout_6.addWidget(self.btn_load)
        self.gridLayout.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Loader", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "  Segement:", None, -1))
        self.box_segement.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "ENV", None, -1))
        self.box_segement.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "PROP", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "  Version: ", None, -1))
        self.box_version.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "layout_model", None, -1))
        self.box_version.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "correct_model", None, -1))
        self.box_version.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "high_model", None, -1))
        self.box_version.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "tex", None, -1))
        self.btn_fresh.setText(QtWidgets.QApplication.translate("MainWindow", "Fresh", None, -1))
        self.btn_freshpreview.setText(QtWidgets.QApplication.translate("MainWindow", "Fresh Generated Preview", None, -1))
        self.btn_load.setText(QtWidgets.QApplication.translate("MainWindow", "Load", None, -1))

