# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'submitter_widgets.ui'
#
# Created: Wed Feb 03 20:46:29 2021
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(483, 498)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 467, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.line_assetname = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line_assetname.setMinimumSize(QtCore.QSize(0, 30))
        self.line_assetname.setObjectName("line_assetname")
        self.horizontalLayout_3.addWidget(self.line_assetname)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btn_getname = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_getname.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_getname.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_getname.setObjectName("btn_getname")
        self.horizontalLayout_3.addWidget(self.btn_getname)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.box_segment = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.box_segment.setMinimumSize(QtCore.QSize(80, 30))
        self.box_segment.setObjectName("box_segment")
        self.box_segment.addItem("")
        self.box_segment.addItem("")
        self.horizontalLayout_4.addWidget(self.box_segment)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.box_version = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.box_version.setMinimumSize(QtCore.QSize(150, 30))
        self.box_version.setObjectName("box_version")
        self.box_version.addItem("")
        self.box_version.addItem("")
        self.box_version.addItem("")
        self.box_version.addItem("")
        self.horizontalLayout_4.addWidget(self.box_version)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.btn_clean = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_clean.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_clean.setObjectName("btn_clean")
        self.verticalLayout.addWidget(self.btn_clean)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.line_outputpath = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line_outputpath.setMinimumSize(QtCore.QSize(0, 30))
        self.line_outputpath.setObjectName("line_outputpath")
        self.horizontalLayout_6.addWidget(self.line_outputpath)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.listWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_5.addWidget(self.listWidget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.btn_grabscreen = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_grabscreen.setMinimumSize(QtCore.QSize(0, 45))
        self.btn_grabscreen.setObjectName("btn_grabscreen")
        self.verticalLayout_2.addWidget(self.btn_grabscreen)
        self.btn_remove = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_remove.setMinimumSize(QtCore.QSize(0, 45))
        self.btn_remove.setObjectName("btn_remove")
        self.verticalLayout_2.addWidget(self.btn_remove)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.btn_submit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_submit.setMinimumSize(QtCore.QSize(0, 60))
        self.btn_submit.setObjectName("btn_submit")
        self.verticalLayout.addWidget(self.btn_submit)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Submitter", None, -1))
        self.btn_getname.setText(QtWidgets.QApplication.translate("MainWindow", "<", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Segment:", None, -1))
        self.box_segment.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "ENV", None, -1))
        self.box_segment.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "PROP", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "    Version:", None, -1))
        self.box_version.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "layout_model", None, -1))
        self.box_version.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "correct_model", None, -1))
        self.box_version.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "high_model", None, -1))
        self.box_version.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "tex", None, -1))
        self.btn_clean.setText(QtWidgets.QApplication.translate("MainWindow", "clean up", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Output path:  ", None, -1))
        self.btn_grabscreen.setText(QtWidgets.QApplication.translate("MainWindow", "Grab Screen", None, -1))
        self.btn_remove.setText(QtWidgets.QApplication.translate("MainWindow", "Remove", None, -1))
        self.btn_submit.setText(QtWidgets.QApplication.translate("MainWindow", "Submit", None, -1))

